apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: frontend
      context: ./app
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - app/k8s/*
deploy:
  kubectl: {}
